# Site settings
title: Katikapalli Lokesh # site title
description: >- # site description
  Computer Vision Researcher specializing in Vision-Language Models and Multimodal AI. 
lang: en-US # default lang
timezone: Asia/Kolkata # set your timezone (fixed typo: Kolkota -> Kolkata)
image: assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
# repo: https://github.com/katikapalli/katikapalli.github.io # site repo [optional]
mode: light # default theme "dark" | "light"

# Profile settings
author:
  name: Katikapalli Lokesh # author name
  bio: >- # tell to the world
    Predoctoral Researcher <br>
    Clinical AI for Healthcare Applications
  
  # AI for Clinical Applications
  # Clinical AI | Multimodal Learning | Reliable ML
  # Vision Language and Learning Group

  username: katikapallilokesh # general username
  github: katikapallilokesh # github username
  twitter: ktpl_lokesh # twitter username
  linkedin: katikapallilokesh # linkedin username
  scholar: 2bmzIgMAAAAJ # google scholar username
  email: katikapalli.lokesh@yahoo.com # email adress
  avatar: /assets/img/Home.jpg # change with your own avatar

# URL settings
url: "https://katikapallilokesh.github.io" # Update with your actual URL
baseurl: ""
permalink: /:title/
google_analytics: GTM-NPV9JNDW # leave it blank if not wish
fb_appid:

# Collection setting
collections:
  posts:
    output: true
  publications:
    output: true
    permalink: /publications/:name/
  projects:
    output: true
    permalink: /projects/:name/

# Markdown settings
markdown: kramdown
kramdown:
  math_engine: mathjax

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false
  - scope:
      path: "_publications"
      type: "publications"
    values:
      layout: "publication"
  - scope:
      path: "_projects"
      type: "projects"
    values:
      layout: "project"

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 5

# Build settings
# theme: klise
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
